### ISSUE TITLE
Trouble with Test Cases

### ISSUE THREAD

**Issue by JWWHouse** [addisonklinke/rainflow#1] opened 2020-04-08 12:39 UTC
Great package. I intend to use it with (to us) very large datasets to track fatigue usage in passive components.  
I'm having some issues with artificial (i.e., test) data.  I need to prove that it is returning expected results from known inputs before I let it hunt through random data.
Everything works as expected with Python Project Rainflow test data, (https://pypi.org/project/rainflow/), but when I create test data with know number of cycles CountCycles either creates errors, returns an empty table, or returns results without summarizing into tables (i.e., returns each cycle discovered instead of binning into summary table. Error summary and test data is attached: TestTimeHistory3.txt is a single amplitude with 100 cycles +/-100. TestTimeHistory4.txt is 100 cycles with amplitude +/-100 and 50 cycles with amplitude +/- 50. TestTimeHistory6.txt is 1650 cycles of 10 different amplitudes, randomized. File AKRainflowError.txt shows some output with error messages or empty output tables.
[AKRainflowError.txt](https://github.com/addisonklinke/rainflow/files/4450444/AKRainflowError.txt)
[TestTimeHistory3.txt](https://github.com/addisonklinke/rainflow/files/4450446/TestTimeHistory3.txt)
[TestTimeHistory4.txt](https://github.com/addisonklinke/rainflow/files/4450448/TestTimeHistory4.txt)
[TestTimeHistory6.txt](https://github.com/addisonklinke/rainflow/files/4450450/TestTimeHistory6.txt)

**Comment by addisonklinke** [comment] 2020-04-17 03:09
Thank you for providing those examples. I have been able to reproduce the error
```
Error in if (abs(rangeX) >= abs(rangeY)) { : 
  missing value where TRUE/FALSE needed
```
It originates from the check for `includesStart` on line 66 of [CountCycles.numeric.R](https://github.com/addisonklinke/rainflow/blob/master/R/CountCycles.numeric.R#L66). In the unusual case where all cycles have identical min/max magnitudes, this branch of the if-statement always executes which I did not foresee as a possibility originally.

I need a bit more time to adjust the loop logic accordingly and test to confirm, but I am confident I can get this resolved in the next few days. I'll let you know when there's an updated version to install and test on your end

**Comment by addisonklinke** [comment] 2020-04-17 22:28
The issue should be resolved as of commit 52cc27f - please remove your local installation and then redo the install from Github. Below is the script I tested with to confirm

```
# Load packages and data
devtools::install_github("addisonklinke/rainflow")
library("rainflow")
test <- read.csv("TestTimeHistory3.txt", header = FALSE, col.names = c("amplitude")) 
x <- test$amplitude

# Confirm the correct "numeric" class
print(class(x))

# Run the rainflow analysis
r <- CountCycles(x)
summary(r)
```

For an example of analyzing a more complex timeseries, please see the included weather data

```
data(weather)
p <- FindPeaks(weather$temp, R = 1.1, smooth = TRUE, window = 120)
r <- CountCycles(p)
summary(r)
plot(r)
```

**Comment by JWWHouse** [comment] 2020-04-20 14:42
Thanks for the fix.  I removed then reinstalled rainflow package per your instructions.  sessionInfo() reports that I have rainflow_0.0.3 loaded - is that correct?

There seems to be a minor bug in the summary results.  See AKRainflowQuery2.txt for descriptions.
1) For the artificial test data "TestTimeHistory3 .txt" printing the resultant object shows 199 1/2 cycles of amplitude 200, but summary reports the 199 1/2 cycles as full cycles vs. 99.5 cycles.  Average amplitude and mean are as expected.

2) I used the Python rainflow continuous oscillating data example (see definition in AKRainflowQuery2.txt) from https://pypi.org/project/rainflow/#description, that I read into R as PythonRainflowTest.csv (attached but renamed *.txt to get around GitHub's conversion to & exclusion of excel)).  Employing FindPeaks returns an amplitude/mean/count table as expected, that contains a total of 7.5 cycles, but summary returns 11 cycles.  The average amplitude and means are correct.

May I suggest that you order the resultant cycle count tables?  I used r2 <- r[order(r$amplitude),] and the table is much more pleasing with no changes in calculated means or sums.

I can use the rainflow functions as they stand, ignoring the summary results and doing the summation /ordering manually, but I though that you'd like a go at understanding the summary problem (or pointing out my mistakes).  Let me know if you'd like me to close out the issue as-is.  Thanks again, JWW

[PythonRainflowTest.txt](https://github.com/addisonklinke/rainflow/files/4504159/PythonRainflowTest.txt)

[AKRainflowQuery2.txt](https://github.com/addisonklinke/rainflow/files/4504154/AKRainflowQuery2.txt)

**Comment by JWWHouse** [comment] 2020-04-20 15:02
Addison,
Thanks for the effort. I believe I removed and reinstalled the package as
you requested.  I ended up with version rainflow_0.0.3.

I left another comment. You can address or not, I don't want to consume too
much of your time. The version I was running seems to have a minor bug in
the summary results. I can work around it, so I will close out the comments
if you wish.

Thanks again for the extra effort to support an old project.
JWW

**Comment by addisonklinke** [comment] 2020-08-15 02:45
@JWWHouse sorry for the long delay, I lost track of things after coronavirus hit. I see the discrepancy you were pointing out with the cycle counts. Looks like I had initially intended the "cycles" portion of the summary to be the number of rows (regardless of half or full cycle). However, that is indeed confusing terminology. I updated this is in https://github.com/addisonklinke/rainflow/commit/794d59bc47a7eea531e3dcbd637127aa51fb9f5b (v0.0.4) to sum and account for half cycles.

I am choosing to leave the cycle table unsorted so that the order of rows reflects their appearance in the original time series. You can always get the sorted version with the code you mentioned, but you cannot go backwards and determine the correct temporal order from the sorted version.

**Closed as completed by addisonklinke** 2020-08-15 02:45 UTC

**Comment by JWWHouse** [comment] 2020-08-16 00:06
I like your idea of keeping the temporal order. Most rain flow  routines
lose that.  You may want to advertise it as a feature in the Github
documentation. Please email me when you update, I usually don't go into
Github, and I'll need to refresh the code we uploaded at the beginning. I
hope all is well, & stay well. JWW
